<?php

namespace Database\Seeders;

use App\Models\Post;
use App\Models\Hashtag;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class FakeBlogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tags = [
            ['name' => 'Growth', 'slug' => 'growth'],
            ['name' => 'Tips', 'slug' => 'tips'],
            ['name' => 'Marketing', 'slug' => 'marketing'],
            ['name' => 'Instagram', 'slug' => 'instagram'],
            ['name' => 'SEO', 'slug' => 'seo'],
            ['name' => 'Social Media', 'slug' => 'social-media'],
            ['name' => 'Influencer', 'slug' => 'influencer'],
            ['name' => 'Content Creation', 'slug' => 'content-creation'],
            ['name' => 'Branding', 'slug' => 'branding'],
        ];

        $tagIds = [];
        foreach ($tags as $tagData) {
            $tag = Hashtag::firstOrCreate(['slug' => $tagData['slug']], ['name' => $tagData['name']]);
            $tagIds[] = $tag->id;
        }



        // Editor.js sample blocks
        $content = [
            'time' => time() * 1000,
            'blocks' => [
                [
                    'id' => Str::random(10),
                    'type' => 'header',
                    'data' => [
                        'text' => 'Introduction to the topic',
                        'level' => 2
                    ]
                ],
                [
                    'id' => Str::random(10),
                    'type' => 'paragraph',
                    'data' => [
                        'text' => 'This is a sample paragraph generated by the seeder to test how Editor.js content is rendered on the public blog.'
                    ]
                ],
                [
                    'id' => Str::random(10),
                    'type' => 'list',
                    'data' => [
                        'style' => 'unordered',
                        'items' => [
                            'First important point',
                            'Second important point',
                            'Third important point'
                        ]
                    ]
                ],
                [
                    'id' => Str::random(10),
                    'type' => 'image',
                    'data' => [
                        'file' => [
                            'url' => 'https://picsum.photos/800/400?random=' . rand(1, 1000)
                        ],
                        'caption' => 'A descriptive image caption',
                        'withBorder' => false,
                        'withBackground' => true,
                        'stretched' => false
                    ]
                ],
                [
                    'id' => Str::random(10),
                    'type' => 'button',
                    'data' => [
                        'text' => 'Download Resource',
                        'link' => 'https://example.com'
                    ]
                ]
            ],
            'version' => '2.28.0'
        ];

        $arContent = [
            'time' => time() * 1000,
            'blocks' => [
                [
                    'id' => Str::random(10),
                    'type' => 'header',
                    'data' => [
                        'text' => 'مقدمة حول الموضوع',
                        'level' => 2
                    ]
                ],
                [
                    'id' => Str::random(10),
                    'type' => 'paragraph',
                    'data' => [
                        'text' => 'هذه فقرة تجريبية تم إنشاؤها بواسطة البذر لاختبار كيفية عرض محتوى Editor.js في المدونة العامة.'
                    ]
                ],
                [
                    'id' => Str::random(10),
                    'type' => 'list',
                    'data' => [
                        'style' => 'unordered',
                        'items' => [
                            'النقطة الهامة الأولى',
                            'النقطة الهامة الثانية',
                            'النقطة الهامة الثالثة'
                        ]
                    ]
                ],
                [
                    'id' => Str::random(10),
                    'type' => 'image',
                    'data' => [
                        'file' => [
                            'url' => 'https://picsum.photos/800/400?random=' . rand(1, 1000)
                        ],
                        'caption' => 'صورة توضيحية للمقال',
                        'withBorder' => false,
                        'withBackground' => true,
                        'stretched' => false
                    ]
                ],
                [
                    'id' => Str::random(10),
                    'type' => 'button',
                    'data' => [
                        'text' => 'تحميل الموارد',
                        'link' => 'https://example.com'
                    ]
                ]
            ],
            'version' => '2.28.0'
        ];

        for ($i = 1; $i <= 15; $i++) {
            $post = Post::create([
                'title' => [
                    'en' => "Amazing Blog Post Title #$i",
                    'ar' => "عنوان مقال رائع ومميز رقم $i"
                ],
                'slug' => [
                    'en' => "amazing-blog-post-title-$i",
                    'ar' => "anwan-maqal-raea-wmmyz-rqm-$i"
                ],
                'content' => [
                    'en' => $content,
                    'ar' => $arContent
                ],
                'is_active' => true,
                'views' => rand(10, 500)
            ]);

            // Attach 2 random tags
            $randomTags = collect($tagIds)->random(2);
            $post->hashtags()->attach($randomTags);

            // Add cover image
            try {
                $post->addMediaFromUrl("https://picsum.photos/seed/post{$i}/800/400")
                     ->toMediaCollection('cover');
            } catch (\Exception $e) {
                // Ignore if download fails
            }
        }

        $this->command->info('FakeBlogSeeder completed! Created 15 posts with tags and cover images.');
    }
}
